lsi: false
safe: true
source: [main]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
title: thomastron's domicile
description: Bookmark this to keep an eye on my project updates!
